### ISSUE TITLE
[Epic] technical Debt

### ISSUE THREAD

**Issue by ndeloof** [cfpio/callForPapers#160]
- [ ] layers over-engineering
- [ ] admin vs restricted REST api with comparable implementation
- [ ] implementations mix
- [ ] verbose code. Adopt lombok and vavr

CFP backend is mostly CRUD, should be trivial code
